# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5baedeb9353de4055313d573410e6135fe86d643c32b3667b0d97d6b8d7d49714d9072028479790a82550933f63f4d4725602c57f3c6221cfd00df44acbd8e6c

test:
  secret_key_base: 8426c5bc65d23266ce35fe25463ddf37e5ef257448dd891ddd4621c0cfb25dbe5f0bfbb9fb0e22cfed92235d466a19aef55bc5a52104155e65e9bf49eefca992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
